
"use client"

import React, { useState, useEffect, useRef, useMemo } from 'react';
import { collection, query, where, getDocs, getDoc, doc, updateDoc, addDoc, serverTimestamp, onSnapshot } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { erpDb } from '@/lib/firebase-erp';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { 
  Calendar, 
  Search, 
  Building2, 
  Loader2, 
  Shield, 
  Database, 
  Terminal,
  CheckCircle2,
  LogOut,
  Clock as ClockIcon,
  Zap,
  MapPin,
  Navigation,
  User,
  ChevronDown,
  X
} from 'lucide-react';

interface ActiveCollaborator {
  id: string;
  fullName: string;
  cedula?: string;
  displayId?: string;
  department?: string;
  status: string;
}

export interface ProjectItem {
  id: string;
  code: string;
  name: string;
  location: string;
  latitude?: number;
  longitude?: number;
}

export const resolveProjectCode = (docId: string, data: any): string => {
  const rawCode = (data?.code || data?.codigo || data?.projectCode || '').toString().trim().toUpperCase();
  const trimmedId = (docId || '').toString().trim().toUpperCase();

  // 1. Si el ID del documento de Firestore es GP-001, GP-002, etc., ese es el código prioritario
  if (trimmedId.startsWith('GP-')) {
    return trimmedId;
  }

  // 2. Si en la data del documento existe el campo code/codigo/projectCode (ej. GP-001)
  if (rawCode && rawCode.startsWith('GP-')) {
    return rawCode;
  }

  if (rawCode) {
    return rawCode;
  }

  // 3. Si el ID del documento no es un ID interno aleatorio de 20 caracteres (como ahyDZw2v8VdLQ1wRoEFX)
  const isAutoGeneratedId = /^[a-zA-Z0-9]{20}$/.test(docId);
  if (!isAutoGeneratedId && trimmedId) {
    return trimmedId;
  }

  return rawCode;
};

export function GuardRegistrationForm() {
  const [currentTime, setCurrentTime] = useState<Date | null>(null);
  const [loading, setLoading] = useState(false);
  const [projectLoading, setProjectLoading] = useState(false);
  const [capturingGps, setCapturingGps] = useState(false);
  const [detectedProject, setDetectedProject] = useState<{
    id?: string;
    code?: string;
    name: string;
    location: string;
    latitude?: number;
    longitude?: number;
  } | null>(null);
  
  const [formData, setFormData] = useState({
    guardName: '',
    projectCode: '',
    duration: '12h',
    shiftType: 'Diurno'
  });

  const { toast } = useToast();

  // Catálogo de Proyectos con Autocompletado (GP-001, GP-002, etc.)
  const [availableProjects, setAvailableProjects] = useState<ProjectItem[]>([]);
  const [showProjectDropdown, setShowProjectDropdown] = useState(false);
  const projectDropdownRef = useRef<HTMLDivElement>(null);

  // Autocompletado de Colaboradores Activos desde ERP ('employees' o 'colaboradores')
  const [activeCollaborators, setActiveCollaborators] = useState<ActiveCollaborator[]>([]);
  const [showColabDropdown, setShowColabDropdown] = useState(false);
  const colabDropdownRef = useRef<HTMLDivElement>(null);
  const isSubmittingRef = useRef(false);

  useEffect(() => {
    let empsDocs: any[] = [];
    let colabsDocs: any[] = [];

    const syncCollaborators = () => {
      const map = new Map<string, ActiveCollaborator>();
      [...empsDocs, ...colabsDocs].forEach(docSnap => {
        const d = docSnap.data ? docSnap.data() : docSnap;
        const status = (d.status || '').toString().trim();
        const isActive = !status || status.toLowerCase() === 'activo';
        const rawName = (d.fullName || d.name || '').toString().trim();
        if (isActive && rawName) {
          const fullName = rawName.toUpperCase();
          if (!map.has(fullName)) {
            map.set(fullName, {
              id: docSnap.id,
              fullName,
              cedula: d.cedula || '',
              displayId: d.displayId || '',
              department: d.department || '',
              status: status || 'Activo'
            });
          }
        }
      });
      const sorted = Array.from(map.values()).sort((a, b) => a.fullName.localeCompare(b.fullName));
      setActiveCollaborators(sorted);
    };

    const unsubEmps = onSnapshot(collection(erpDb, 'employees'), (snap) => {
      empsDocs = snap.docs;
      syncCollaborators();
    }, (err) => {
      console.warn("ERP employees listener warning:", err);
    });

    const unsubColabs = onSnapshot(collection(erpDb, 'colaboradores'), (snap) => {
      colabsDocs = snap.docs;
      syncCollaborators();
    }, () => {});

    return () => {
      unsubEmps();
      unsubColabs();
    };
  }, []);

  // Suscripción en tiempo real a la colección 'projects'
  useEffect(() => {
    const unsubProjects = onSnapshot(collection(db, 'projects'), (snapshot) => {
      const projectMap = new Map<string, ProjectItem>();
      snapshot.docs.forEach(docSnap => {
        const d = docSnap.data();
        const cleanCode = resolveProjectCode(docSnap.id, d);
        const name = (d.name || d.nombre || 'Sitio Sin Nombre').trim();
        const location = (d.location || 'UBICACIÓN REGISTRADA').trim();
        
        // Clave única por código o nombre para evitar duplicados en el selector
        const key = cleanCode || docSnap.id;
        if (!projectMap.has(key)) {
          projectMap.set(key, {
            id: docSnap.id,
            code: cleanCode,
            name,
            location,
            latitude: d.latitude ?? d.lat,
            longitude: d.longitude ?? d.lng
          });
        }
      });

      const list = Array.from(projectMap.values()).sort((a, b) => {
        if (a.code && b.code) return a.code.localeCompare(b.code, undefined, { numeric: true });
        return a.name.localeCompare(b.name);
      });
      setAvailableProjects(list);
    }, (err) => {
      console.warn("Error al cargar proyectos en Comando Guardia:", err);
    });

    return () => unsubProjects();
  }, []);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (colabDropdownRef.current && !colabDropdownRef.current.contains(event.target as Node)) {
        setShowColabDropdown(false);
      }
      if (projectDropdownRef.current && !projectDropdownRef.current.contains(event.target as Node)) {
        setShowProjectDropdown(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const filteredCollaborators = useMemo(() => {
    const q = formData.guardName.trim().toUpperCase();
    if (!q) {
      return activeCollaborators.slice(0, 8);
    }
    return activeCollaborators
      .filter(c => 
        c.fullName.includes(q) || 
        (c.cedula && c.cedula.includes(q)) ||
        (c.displayId && c.displayId.toUpperCase().includes(q))
      )
      .slice(0, 12);
  }, [activeCollaborators, formData.guardName]);

  const handleSelectCollaborator = (colab: ActiveCollaborator) => {
    setFormData(prev => ({
      ...prev,
      guardName: colab.fullName
    }));
    setShowColabDropdown(false);
  };

  // Filtrado de proyectos para el autocompletado en Comando Guardia
  const filteredProjects = useMemo(() => {
    const q = formData.projectCode.trim().toUpperCase();
    if (!q) {
      return availableProjects.slice(0, 10);
    }
    return availableProjects.filter(p => 
      p.code.toUpperCase().includes(q) ||
      p.name.toUpperCase().includes(q) ||
      p.location.toUpperCase().includes(q) ||
      (p.id.toUpperCase().startsWith('GP-') && p.id.toUpperCase().includes(q))
    ).slice(0, 12);
  }, [availableProjects, formData.projectCode]);

  // Selección de proyecto desde el autocompletado:
  // Se asegura de guardar SIEMPRE el código de puesto (GP-001, GP-002, etc.) y NUNCA el ID interno de Firestore (ej. ahyDZw2v8VdLQ1wRoEFX)
  const handleSelectProject = (proj: ProjectItem) => {
    const cleanCode = (
      (proj.code && proj.code.toUpperCase().startsWith('GP-') ? proj.code : '') ||
      (proj.id && proj.id.toUpperCase().startsWith('GP-') ? proj.id : '') ||
      proj.code ||
      (!/^[a-zA-Z0-9]{20}$/.test(proj.id) ? proj.id : '') ||
      'GP-001'
    ).trim().toUpperCase();

    setFormData(prev => ({
      ...prev,
      projectCode: cleanCode
    }));

    setDetectedProject({
      id: proj.id, // Para referencias de actualización interna como GPS
      code: cleanCode,
      name: proj.name,
      location: proj.location,
      latitude: proj.latitude,
      longitude: proj.longitude
    });

    if (typeof window !== 'undefined' && cleanCode) {
      sessionStorage.setItem('project-code', cleanCode);
    }

    setShowProjectDropdown(false);
  };

  useEffect(() => {
    setCurrentTime(new Date());
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    const searchProject = async () => {
      const code = formData.projectCode.trim().toUpperCase();
      if (code.length >= 2) {
        // Primero buscar en el catálogo en memoria
        const matchedInMemory = availableProjects.find(p => 
          p.code.toUpperCase() === code || 
          p.id.toUpperCase() === code ||
          p.name.toUpperCase() === code
        );

        if (matchedInMemory) {
          const cleanCode = matchedInMemory.code || (matchedInMemory.id.startsWith('GP-') ? matchedInMemory.id : code);
          setDetectedProject({
            id: matchedInMemory.id,
            code: cleanCode,
            name: matchedInMemory.name,
            location: matchedInMemory.location,
            latitude: matchedInMemory.latitude,
            longitude: matchedInMemory.longitude
          });
          if (typeof window !== 'undefined' && cleanCode) {
            sessionStorage.setItem('project-code', cleanCode);
          }
          return;
        }

        setProjectLoading(true);
        try {
          // Búsqueda por campo code
          const q = query(collection(db, 'projects'), where('code', '==', code));
          const snapshot = await getDocs(q);
          if (!snapshot.empty) {
            const d = snapshot.docs[0];
            const data = d.data();
            const cleanCode = resolveProjectCode(d.id, data) || code;
            setDetectedProject({ 
              id: d.id,
              code: cleanCode,
              name: data.name || data.nombre || 'Sitio Registrado', 
              location: data.location || 'UBICACIÓN REGISTRADA',
              latitude: data.latitude ?? data.lat,
              longitude: data.longitude ?? data.lng
            });
            if (typeof window !== 'undefined') {
              sessionStorage.setItem('project-code', cleanCode);
            }
          } else {
            // Intentar por ID directo si el ID es GP-001, etc.
            const directRef = doc(db, 'projects', code);
            const directSnap = await getDoc(directRef);
            if (directSnap.exists()) {
              const data = directSnap.data();
              const cleanCode = resolveProjectCode(directSnap.id, data) || code;
              setDetectedProject({ 
                id: directSnap.id,
                code: cleanCode,
                name: data.name || data.nombre || 'Sitio Registrado', 
                location: data.location || 'UBICACIÓN REGISTRADA',
                latitude: data.latitude ?? data.lat,
                longitude: data.longitude ?? data.lng
              });
              if (typeof window !== 'undefined') {
                sessionStorage.setItem('project-code', cleanCode);
              }
            } else {
              setDetectedProject(null);
            }
          }
        } catch (err) {
          console.error("Error al buscar proyecto en Firestore:", err);
        } finally {
          setProjectLoading(false);
        }
      } else {
        setDetectedProject(null);
      }
    };

    const debounce = setTimeout(searchProject, 400);
    return () => clearTimeout(debounce);
  }, [formData.projectCode, availableProjects]);

  const handleCaptureLocation = async () => {
    const code = formData.projectCode.trim().toUpperCase();
    if (!code) {
      toast({
        title: "CÓDIGO DE PUESTO REQUERIDO",
        description: "Ingrese el código de proyecto para capturar su ubicación GPS.",
        variant: "destructive"
      });
      return;
    }

    if (!navigator.geolocation) {
      toast({
        title: "SIN GEOLOCALIZACIÓN",
        description: "Su dispositivo no soporta geolocalización.",
        variant: "destructive"
      });
      return;
    }

    setCapturingGps(true);
    navigator.geolocation.getCurrentPosition(
      async (pos) => {
        const latitude = pos.coords.latitude;
        const longitude = pos.coords.longitude;
        try {
          let targetDocRef: any = null;

          if (detectedProject?.id) {
            targetDocRef = doc(db, 'projects', detectedProject.id);
          } else {
            const q = query(collection(db, 'projects'), where('code', '==', code));
            const snapshot = await getDocs(q);
            if (!snapshot.empty) {
              targetDocRef = doc(db, 'projects', snapshot.docs[0].id);
            } else {
              const directRef = doc(db, 'projects', code);
              const directSnap = await getDoc(directRef);
              if (directSnap.exists()) {
                targetDocRef = directRef;
              }
            }
          }

          if (!targetDocRef) {
            toast({
              title: "PUESTO NO ENCONTRADO",
              description: `No se encontró un documento en la colección 'projects' con el código ${code}.`,
              variant: "destructive"
            });
            setCapturingGps(false);
            return;
          }

          // ACTUALIZAR DOCUMENTO EN FIRESTORE CON updateDoc
          // Guardar SOLO: latitude, longitude y mappedAt con timestamp.
          // El campo name ya existe en el documento, no hace falta guardarlo de nuevo.
          await updateDoc(targetDocRef, {
            latitude,
            longitude,
            mappedAt: serverTimestamp()
          });

          setDetectedProject(prev => prev ? {
            ...prev,
            latitude,
            longitude
          } : null);

          toast({
            title: "UBICACIÓN CAPTURADA",
            description: `Coordenadas (${latitude.toFixed(5)}, ${longitude.toFixed(5)}) guardadas en Firestore para el puesto actual. PACSA Console refleja la posición en el mapa.`,
            className: "bg-emerald-950 border-emerald-500 text-white"
          });
        } catch (err) {
          console.error("Error al guardar GPS:", err);
          toast({
            title: "ERROR AL GUARDAR",
            description: "No se pudieron actualizar las coordenadas en Firestore.",
            variant: "destructive"
          });
        } finally {
          setCapturingGps(false);
        }
      },
      (err) => {
        setCapturingGps(false);
        toast({
          title: "ERROR GPS",
          description: "No se pudo obtener la posición satelital del puesto.",
          variant: "destructive"
        });
      },
      { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmittingRef.current) return;
    if (!formData.guardName || !formData.projectCode) {
      toast({
        title: "INFORMACIÓN FALTANTE",
        description: "Debe completar el nombre y el código de proyecto.",
        variant: "destructive"
      });
      return;
    }

    isSubmittingRef.current = true;
    setLoading(true);
    try {
      // Garantizar que projectCode se guarde SIEMPRE con el código human-readable (GP-001, GP-002, etc.)
      // y NUNCA con un hash interno de Firestore como ahyDZw2v8VdLQ1wRoEFX
      let cleanCode = formData.projectCode.trim().toUpperCase();

      // Si el código actual parece ser un hash autogenerado de Firestore (20 caracteres alfanuméricos)
      if (/^[a-zA-Z0-9]{20}$/.test(cleanCode)) {
        const matched = availableProjects.find(p => p.id === cleanCode);
        if (matched && matched.code) {
          cleanCode = matched.code.toUpperCase();
        }
      }

      // Priorizar el código limpio detectado si empieza con GP-
      if (detectedProject?.code && detectedProject.code.startsWith('GP-')) {
        cleanCode = detectedProject.code.toUpperCase();
      }

      await addDoc(collection(db, 'shift-registrations'), {
        guardName: formData.guardName.trim().toUpperCase(),
        projectCode: cleanCode,
        clientName: detectedProject?.name || 'Cliente por Validar',
        projectName: detectedProject?.name || 'Sitio No Identificado',
        projectLocation: detectedProject?.location || 'UBICACIÓN NO ESPECIFICADA',
        shiftType: formData.shiftType,
        duration: formData.duration,
        shiftDuration: formData.duration,
        entryTime: serverTimestamp(),
        exitTime: null,
        status: formData.duration === '24h' ? 'Doble' : 'Activo'
      });
      
      toast({
        title: "REGISTRO EXITOSO",
        description: `El elemento ${formData.guardName} ha sido sincronizado en el puesto [${cleanCode}].`,
        variant: "default"
      });
      
      setFormData({ guardName: '', projectCode: '', duration: '12h', shiftType: 'Diurno' });
      setDetectedProject(null);
    } catch (err) {
      toast({
        title: "ERROR DE CONEXIÓN",
        description: "No se pudo sincronizar el registro con el servidor.",
        variant: "destructive"
      });
    } finally {
      isSubmittingRef.current = false;
      setLoading(false);
    }
  };

  // Registrar salida del guardia: Buscar en shift-registrations con query donde guardName == nombre del guardia Y projectCode == código del puesto.
  // De todos los resultados encontrados, filtrar en el código JavaScript (no en Firestore) el que no tenga exitTime o tenga exitTime igual a null.
  // Actualizar ese documento con updateDoc agregando exitTime con serverTimestamp() y status 'completado'. No usar addDoc.
  const handleRegisterExit = async () => {
    if (!formData.guardName || !formData.projectCode) {
      toast({
        title: "DATOS REQUERIDOS",
        description: "Debe ingresar el nombre del elemento y el código del puesto para registrar la salida.",
        variant: "destructive"
      });
      return;
    }

    if (isSubmittingRef.current) return;
    isSubmittingRef.current = true;
    setLoading(true);
    try {
      const guardNameUpper = formData.guardName.trim().toUpperCase();
      let projectCodeUpper = formData.projectCode.trim().toUpperCase();

      // Resolver a código limpio GP- si es un hash de Firestore
      if (/^[a-zA-Z0-9]{20}$/.test(projectCodeUpper)) {
        const matched = availableProjects.find(p => p.id === projectCodeUpper);
        if (matched && matched.code) {
          projectCodeUpper = matched.code.toUpperCase();
        }
      }
      if (detectedProject?.code && detectedProject.code.startsWith('GP-')) {
        projectCodeUpper = detectedProject.code.toUpperCase();
      }

      // Buscar en shift-registrations con query donde guardName == nombre del guardia Y projectCode == código del puesto
      const q = query(
        collection(db, 'shift-registrations'),
        where('guardName', '==', guardNameUpper),
        where('projectCode', '==', projectCodeUpper)
      );
      let snapshot = await getDocs(q);

      // Respaldo por si existen registros antiguos que se guardaron con el ID interno
      if (snapshot.empty && detectedProject?.id && detectedProject.id !== projectCodeUpper) {
        const qLegacy = query(
          collection(db, 'shift-registrations'),
          where('guardName', '==', guardNameUpper),
          where('projectCode', '==', detectedProject.id)
        );
        const snapLegacy = await getDocs(qLegacy);
        if (!snapLegacy.empty) {
          snapshot = snapLegacy;
        }
      }

      // De todos los resultados encontrados, filtrar en el código JavaScript (no en Firestore) el que no tenga exitTime o tenga exitTime igual a null
      const activeDocs = snapshot.docs.filter(docItem => {
        const data = docItem.data();
        return !data.exitTime || data.exitTime === null;
      });

      if (activeDocs.length > 0) {
        // En caso de múltiples turnos activos, seleccionar el más reciente según entryTime
        activeDocs.sort((a, b) => {
          const timeA = a.data().entryTime?.toMillis?.() || (a.data().entryTime?.seconds ? a.data().entryTime.seconds * 1000 : 0);
          const timeB = b.data().entryTime?.toMillis?.() || (b.data().entryTime?.seconds ? b.data().entryTime.seconds * 1000 : 0);
          return timeB - timeA;
        });

        const targetDoc = activeDocs[0];

        // Actualizar ese documento con updateDoc agregando exitTime con serverTimestamp() y status 'completado'. No usar addDoc.
        await updateDoc(doc(db, 'shift-registrations', targetDoc.id), {
          exitTime: serverTimestamp(),
          status: 'completado'
        });

        toast({
          title: "SALIDA REGISTRADA",
          description: `Salida de ${guardNameUpper} en puesto [${projectCodeUpper}] registrada con éxito (estado: completado).`,
          variant: "default"
        });

        setFormData({ guardName: '', projectCode: '', duration: '12h', shiftType: 'Diurno' });
        setDetectedProject(null);
      } else {
        toast({
          title: "TURNO ACTIVO NO ENCONTRADO",
          description: `No se encontró un registro de entrada activo para ${guardNameUpper} en el puesto [${projectCodeUpper}].`,
          variant: "destructive"
        });
      }
    } catch (err) {
      console.error("Error al registrar salida:", err);
      toast({
        title: "ERROR AL REGISTRAR SALIDA",
        description: "No se pudo actualizar el registro con la salida.",
        variant: "destructive"
      });
    } finally {
      isSubmittingRef.current = false;
      setLoading(false);
    }
  };

  const getEstimatedExit = () => {
    if (!currentTime) return '--:--';
    const hours = parseInt(formData.duration) || 8;
    const exitDate = new Date(currentTime.getTime() + hours * 60 * 60 * 1000);
    return exitDate.toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit', hour12: false });
  };

  const formattedDate = currentTime?.toLocaleDateString('es-MX', { 
    weekday: 'long', 
    day: 'numeric', 
    month: 'long', 
    year: 'numeric' 
  });

  const formattedTime = currentTime?.toLocaleTimeString('es-MX', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false
  });

  const durationOptions = Array.from({ length: 17 }, (_, i) => i + 8);

  return (
    <div className="bg-[#12121c] border border-white/5 rounded-3xl shadow-2xl overflow-hidden animate-in fade-in duration-700">
      <div className="p-8 bg-[#1a1b2e]/80 border-b border-white/5 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="bg-primary/20 p-3 rounded-2xl border border-primary/30">
            <Shield className="h-8 w-8 text-primary" />
          </div>
          <div>
            <h2 className="text-3xl font-black tracking-tighter text-white uppercase leading-none">Comando Guardia</h2>
            <div className="flex flex-col mt-1">
              <span className="text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] leading-none mt-0.5">Terminal Sincronizada</span>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-end gap-1">
          <Badge className="bg-primary/10 text-primary border-primary/20 text-[8px] font-black tracking-widest px-3 py-1">
            <Database className="h-2.5 w-2.5 mr-1.5" />
            REAL-TIME SYNC
          </Badge>
        </div>
      </div>

      <div className="p-8 space-y-8">
        <div className="flex items-center gap-3 text-primary/70">
          <Terminal className="h-5 w-5" />
          <h3 className="text-xs font-black uppercase tracking-[0.3em]">Terminal de Registro Táctico</h3>
        </div>

        <div className="bg-[#1a1b2e] border border-white/5 rounded-3xl p-6 shadow-lg space-y-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-secondary/30 rounded-2xl border border-white/5">
                <Calendar className="h-6 w-6 text-primary" />
              </div>
              <div className="space-y-1">
                <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest">Fecha Operativa</p>
                <p className="text-base font-black text-white capitalize">{formattedDate}</p>
              </div>
            </div>
            <div className="text-right space-y-1">
              <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest">Reloj de Comando</p>
              <p className="text-4xl font-black font-mono text-primary leading-none tracking-tighter">{formattedTime}</p>
            </div>
          </div>

          <div className="pt-4 border-t border-white/5 flex items-center justify-around">
            <div className="text-center space-y-1">
              <p className="text-[9px] font-black text-muted-foreground uppercase tracking-widest flex items-center justify-center gap-1.5">
                <ClockIcon className="h-3 w-3" /> Hora Entrada
              </p>
              <p className="text-xl font-black text-white font-mono">{formattedTime}</p>
            </div>
            <div className="h-10 w-[1px] bg-white/5" />
            <div className="text-center space-y-1">
              <p className="text-[9px] font-black text-accent uppercase tracking-widest flex items-center justify-center gap-1.5">
                <LogOut className="h-3 w-3" /> Término Turno
              </p>
              <p className="text-xl font-black text-accent font-mono">{getEstimatedExit()}</p>
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-8">
          <div className="space-y-3 relative" ref={colabDropdownRef}>
            <div className="flex items-center justify-between">
              <Label className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground ml-1">
                Nombre del Elemento
              </Label>
              {activeCollaborators.length > 0 && (
                <span className="text-[9px] font-bold text-emerald-400/80 flex items-center gap-1">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                  {activeCollaborators.length} Colaboradores Activos (ERP)
                </span>
              )}
            </div>
            <div className="relative">
              <input 
                placeholder="NOMBRE Y APELLIDO" 
                value={formData.guardName}
                onFocus={() => setShowColabDropdown(true)}
                onChange={(e) => {
                  setFormData({...formData, guardName: e.target.value.toUpperCase()});
                  setShowColabDropdown(true);
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Escape') setShowColabDropdown(false);
                }}
                className="w-full h-16 bg-[#1a1b2e] border border-white/5 focus:ring-1 focus:ring-primary/50 text-base font-black tracking-tight rounded-2xl pl-6 pr-12 text-white outline-none"
              />
              <div className="absolute right-6 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground">
                <User className="h-5 w-5 text-primary/60" />
              </div>
            </div>

            {/* Menú desplegable de autocompletado */}
            {showColabDropdown && filteredCollaborators.length > 0 && (
              <div className="absolute left-0 right-0 top-full mt-2 z-50 bg-[#161726] border border-primary/20 rounded-2xl shadow-2xl overflow-hidden backdrop-blur-xl max-h-64 overflow-y-auto">
                <div className="px-4 py-2 bg-white/5 border-b border-white/5 flex items-center justify-between text-[9px] font-black uppercase tracking-wider text-muted-foreground">
                  <span>Colaboradores Activos ({filteredCollaborators.length})</span>
                  <span className="text-primary font-bold">Clic para autocompletar</span>
                </div>
                <div className="p-1.5 space-y-0.5">
                  {filteredCollaborators.map((colab) => (
                    <button
                      key={colab.id}
                      type="button"
                      onClick={() => handleSelectCollaborator(colab)}
                      className="w-full text-left px-3.5 py-2.5 rounded-xl hover:bg-primary/20 flex items-center justify-between group transition-colors cursor-pointer"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <div className="h-8 w-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0 group-hover:bg-primary group-hover:text-black transition-colors">
                          <User className="h-4 w-4 text-primary group-hover:text-black" />
                        </div>
                        <div className="truncate">
                          <p className="text-xs font-black uppercase text-white group-hover:text-primary transition-colors truncate">
                            {colab.fullName}
                          </p>
                          <div className="flex items-center gap-2 text-[9px] text-muted-foreground font-mono">
                            {colab.cedula && <span>CÉD: {colab.cedula}</span>}
                            {colab.displayId && <span>• {colab.displayId}</span>}
                            {colab.department && <span>• {colab.department}</span>}
                          </div>
                        </div>
                      </div>
                      <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/30 text-[8px] font-black uppercase shrink-0">
                        Activo
                      </Badge>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="space-y-3 relative" ref={projectDropdownRef}>
            <div className="flex items-center justify-between">
              <Label className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground ml-1">
                Código de Proyecto / Puesto Asignado
              </Label>
              {availableProjects.length > 0 && (
                <span className="text-[9px] font-mono font-bold text-primary/80 uppercase">
                  {availableProjects.length} PUESTOS DISPONIBLES
                </span>
              )}
            </div>
            <div className="relative">
              <input 
                id="input-project-code-guardia"
                placeholder="SELECCIONAR O ESCRIBIR (EJ: GP-001, GP-002)..." 
                value={formData.projectCode}
                onFocus={() => setShowProjectDropdown(true)}
                onChange={(e) => {
                  setFormData({...formData, projectCode: e.target.value.toUpperCase()});
                  setShowProjectDropdown(true);
                }}
                className="w-full h-16 bg-[#1a1b2e] border border-white/5 focus:ring-1 focus:ring-primary/50 font-mono text-base font-black tracking-widest rounded-2xl pl-6 pr-24 text-white outline-none"
              />
              <div className="absolute right-4 top-1/2 -translate-y-1/2 flex items-center gap-2">
                {formData.projectCode && (
                  <button
                    type="button"
                    onClick={() => {
                      setFormData({ ...formData, projectCode: '' });
                      setDetectedProject(null);
                      setShowProjectDropdown(true);
                    }}
                    className="p-1.5 hover:bg-white/10 rounded-lg text-muted-foreground hover:text-white transition-colors"
                    title="Limpiar código"
                  >
                    <X className="h-4 w-4" />
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => setShowProjectDropdown(prev => !prev)}
                  className="p-1.5 hover:bg-white/10 rounded-lg text-muted-foreground hover:text-white transition-colors"
                  title="Ver catálogo de puestos"
                >
                  <ChevronDown className={cn("h-4 w-4 transition-transform duration-200", showProjectDropdown && "rotate-180")} />
                </button>
                {projectLoading ? (
                  <Loader2 className="h-5 w-5 animate-spin text-primary" />
                ) : (
                  <Search className="h-5 w-5 text-muted-foreground opacity-50" />
                )}
              </div>
            </div>

            {/* Menú de Autocompletado de Proyectos */}
            {showProjectDropdown && (
              <div className="absolute left-0 right-0 top-full mt-2 z-50 bg-[#161726] border border-white/10 rounded-2xl shadow-2xl shadow-black/80 overflow-hidden backdrop-blur-xl">
                <div className="p-3 border-b border-white/5 bg-white/[0.02] flex items-center justify-between">
                  <span className="text-[10px] font-black uppercase tracking-widest text-primary flex items-center gap-1.5">
                    <Building2 className="h-3.5 w-3.5 text-primary" />
                    Catálogo de Puestos ({filteredProjects.length})
                  </span>
                  <span className="text-[9px] font-mono text-muted-foreground">
                    Asigna código GP oficial
                  </span>
                </div>
                <div className="max-h-64 overflow-y-auto divide-y divide-white/5">
                  {filteredProjects.length === 0 ? (
                    <div className="p-4 text-center text-xs text-muted-foreground font-mono">
                      No se encontraron puestos que coincidan con &quot;{formData.projectCode}&quot;.
                    </div>
                  ) : (
                    filteredProjects.map((proj) => {
                      const isSelected = formData.projectCode === proj.code;
                      return (
                        <button
                          key={proj.id}
                          type="button"
                          onClick={() => handleSelectProject(proj)}
                          className={cn(
                            "w-full px-4 py-3 text-left transition-colors flex items-center justify-between gap-3 group",
                            isSelected 
                              ? "bg-primary/20 hover:bg-primary/25 border-l-4 border-primary" 
                              : "hover:bg-white/5"
                          )}
                        >
                          <div className="flex items-center gap-3 min-w-0">
                            <span className="px-2.5 py-1 rounded-md bg-primary/20 border border-primary/40 text-primary font-mono font-black text-xs shrink-0 tracking-wider">
                              {proj.code}
                            </span>
                            <div className="min-w-0">
                              <p className="text-xs font-black uppercase text-white tracking-wide truncate group-hover:text-primary transition-colors">
                                {proj.name}
                              </p>
                              <p className="text-[10px] text-muted-foreground truncate flex items-center gap-1 mt-0.5">
                                <MapPin className="h-2.5 w-2.5 shrink-0 text-red-400" />
                                {proj.location}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 shrink-0">
                            {typeof proj.latitude === 'number' && (
                              <Badge variant="outline" className="bg-emerald-500/10 text-emerald-400 border-emerald-500/30 text-[8px] font-mono font-bold flex items-center gap-1">
                                <Navigation className="h-2 w-2" />
                                GPS
                              </Badge>
                            )}
                            <Badge variant="outline" className="bg-white/5 text-muted-foreground border-white/10 text-[8px] font-black uppercase">
                              Seleccionar
                            </Badge>
                          </div>
                        </button>
                      );
                    })
                  )}
                </div>
              </div>
            )}
          </div>

          <div className={`bg-[#1a1b2e] border-2 border-dashed rounded-3xl p-6 transition-all duration-500 ${detectedProject ? 'border-primary/40 bg-primary/5' : 'border-white/5'}`}>
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4">
                <div className={`p-3 rounded-2xl ${detectedProject ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'bg-white/5 text-muted-foreground'}`}>
                  {detectedProject ? <CheckCircle2 className="h-6 w-6" /> : <Building2 className="h-6 w-6" />}
                </div>
                <div className="flex flex-col">
                  <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Validación de Destino</span>
                  <p className={`text-sm font-black uppercase italic tracking-tighter mt-1 ${detectedProject ? 'text-white' : 'text-muted-foreground/30'}`}>
                    {detectedProject ? detectedProject.name : 'Esperando ID operativo...'}
                  </p>
                  {detectedProject && (
                    <div className="flex flex-wrap items-center gap-2 mt-1">
                      <span className="text-[9px] font-bold text-primary/70 uppercase tracking-widest">
                        {detectedProject.location}
                      </span>
                      {typeof detectedProject.latitude === 'number' && (
                        <span className="text-[9px] font-mono font-bold text-emerald-400 bg-emerald-950/60 border border-emerald-500/30 px-2 py-0.5 rounded-full flex items-center gap-1">
                          <Navigation className="h-2 w-2" />
                          GPS: {detectedProject.latitude.toFixed(4)}, {detectedProject.longitude?.toFixed(4)}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {formData.projectCode.trim().length >= 2 && (
                <Button
                  id="btn-capturar-ubicacion-puesto-form"
                  type="button"
                  onClick={handleCaptureLocation}
                  disabled={capturingGps}
                  className="h-11 px-4 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-black uppercase tracking-wider rounded-xl flex items-center gap-2 shadow-lg shadow-emerald-950/40"
                >
                  {capturingGps ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Capturando GPS...</span>
                    </>
                  ) : (
                    <>
                      <Navigation className="h-4 w-4" />
                      <span>Capturar ubicación del puesto</span>
                    </>
                  )}
                </Button>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">Duración Jornada</Label>
              <Select value={formData.duration} onValueChange={(v) => setFormData({...formData, duration: v})}>
                <SelectTrigger className="h-14 bg-[#1a1b2e] border-white/5 rounded-2xl font-black uppercase text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-[#1a1b2e] border-white/10 max-h-60">
                  {durationOptions.map((hours) => (
                    <SelectItem key={hours} value={`${hours}h`} className="font-black text-[10px] uppercase">
                      {hours} Horas {hours === 24 ? '(DOBLE)' : ''}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">Turno Operativo</Label>
              <Select value={formData.shiftType} onValueChange={(v) => setFormData({...formData, shiftType: v})}>
                <SelectTrigger className="h-14 bg-[#1a1b2e] border-white/5 rounded-2xl font-black uppercase text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-[#1a1b2e] border-white/10">
                  <SelectItem value="Diurno" className="font-black text-[10px] uppercase">DIURNO</SelectItem>
                  <SelectItem value="Nocturno" className="font-black text-[10px] uppercase">NOCTURNO</SelectItem>
                  <SelectItem value="Mixto" className="font-black text-[10px] uppercase">MIXTO</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Button 
              id="btn-registrar-entrada"
              type="submit" 
              disabled={loading}
              className="w-full h-20 bg-primary hover:bg-primary/90 text-primary-foreground font-black uppercase tracking-[0.2em] rounded-3xl shadow-[0_15px_40px_rgba(59,130,246,0.3)] transition-all duration-300 hover:scale-[1.01] active:scale-[0.98] group cursor-pointer"
            >
              {loading ? "SINCRONIZANDO..." : (
                <span className="flex items-center gap-3">
                  <Zap className="h-5 w-5 fill-primary-foreground group-hover:animate-bounce" />
                  REGISTRAR ENTRADA
                </span>
              )}
            </Button>

            <Button 
              id="btn-registrar-salida"
              type="button" 
              onClick={handleRegisterExit}
              disabled={loading}
              className="w-full h-20 bg-amber-600 hover:bg-amber-500 text-white font-black uppercase tracking-[0.2em] rounded-3xl shadow-[0_15px_40px_rgba(217,119,6,0.3)] transition-all duration-300 hover:scale-[1.01] active:scale-[0.98] group cursor-pointer"
            >
              {loading ? "SINCRONIZANDO..." : (
                <span className="flex items-center gap-3">
                  <LogOut className="h-5 w-5" />
                  REGISTRAR SALIDA
                </span>
              )}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
